name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Unit Tests
      run: dotnet test ApexClearing.SDK.UnitTests/ApexClearing.SDK.UnitTests.csproj --no-build --verbosity normal

    - name: Integration Test
      run: dotnet test ApexClearing.SDK.IntegrationTests/ApexClearing.SDK.IntegrationTests.csproj --no-build --verbosity normal
      if: ${{ false }}
      env:
        APEXCLEARING_USERNAME: ${{ secrets.APEXCLEARING_USERNAME }}
        APEXCLEARING_ENTITY: ${{ secrets.APEXCLEARING_ENTITY }}
        APEXCLEARING_SHAREDSECRET: ${{ secrets.APEXCLEARING_SHAREDSECRET }}

    - name: Pack NuGet
      run: dotnet pack ApexClearing.SDK/ApexClearing.SDK.csproj -c Release

    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ApexClearing.SDK/bin/Release
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: "ApexClearing.SDK"
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: true
        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: "v*"
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: "https://api.nuget.org"
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: false
